language: cpp
dist: xenial
os: linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libstdc++-7-dev
      - ninja-build

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

before_script:
  - mkdir build
  - cd build
  - cmake -G Ninja ..

script: ninja && ./tests --gtest_repeat=10 --gtest_shuffle
